### ISSUE TITLE
i couldn't download it 

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [qewer33/Exquisite#1]
The installation of /tmp/rgEEjq-exquisite.kwinscript failed because the downloaded package does not contain any useful metadata information, which means that it is not a valid "KPackage" object.

**Comment by jojojojojoj5564656465465** [comment]
i am on fedora

**Comment by qewer33** [comment]
Seems like some other people are experiencing this as well, I'll be taking a look.

**Comment by qewer33** [comment]
For now you can download https://github.com/qewer33/Exquisite/raw/main/exquisite.kwinscript and install it with the `Install from File` button on `System Settings > Window Management > KWin Scripts`

**Comment by qewer33** [comment]
Should be fixed now, please confirm

**Comment by jojojojojoj5564656465465** [comment]
Thanks a lot I love your concept
