### ISSUE TITLE
Need a better general description for non-Windows people

### ISSUE THREAD

**Issue by phord** [qewer33/Exquisite#16]
As someone who has never used Windows 11 (or 10, 8, 7 or Vista), this description is meaningless to me:

> a KWin script that brings Windows 11 like window tiling to KDE Plasma

The rest of the readme talks about configuring the script, but not about what it can do for me.  How would you market the "Windows 11 like" feature that Exquisite offers to someone like me?

btw - I also have not used a Mac.  I've only used Linux since about 2008.

**Comment by qewer33** [comment]
Fair criticism, updated the general description to be a little more explanatory

> The rest of the readme talks about configuring the script, but not about what it can do for me

The "Usage" section is meant to do that actually, it also includes a video (although it is a bit outdated, need to update that)

**Comment by phord** [comment]
The video is distracting in that has several unfamiliar text consoles running animated displays across them. It's hard to figure out what window is the Exquisite window and how the pipes(?) demo is related or not.
