### ISSUE TITLE
shortcut key

### ISSUE THREAD

**Issue by IF-tiger** [qewer33/Exquisite#17]
I like this widget Please add the ESC key after I activate the window, so that I can exit the window without clicking X to close, thank you

**Comment by jayarmstrong** [comment]
> I like this widget Please add the ESC key after I activate the window, so that I can exit the window without clicking X to close, thank you

One workaround is to hit the Exquisite shortcut key a second time. It will do what you want. 

I think adding ESC would be great for new users and more intuitive design. I believe all similar Kwin window effects have ESC exit the effect by default.

**Comment by IF-tiger** [comment]
> > 我喜欢这个小部件 请在激活窗口后添加ESC键，这样我就可以在不单击X关闭的情况下退出窗口，谢谢
> 
> 一种解决方法是再次按“精致”快捷键。它会做你想做的事。
> 
> 我认为添加ESC对于新用户和更直观的设计来说会很棒。我相信所有类似的Kwin窗口效果都有ESC退出效果默认。

yes, i can use shortcut key again, Esc is still necessary

**Comment by qewer33** [comment]
I tried to implement this but couldn't find a way to do it with QtQuick and the KWin API, PlasmaCore.Popup doesn't seem to listen to keyboard events unless you explicitly focus it which would defeat the point of Exquisite since it tries to tile the currently focused window.

**Comment by qewer33** [comment]
This has now been implemented and will be on the next release.
