### ISSUE TITLE
feature request: rename rowspan and columnspan to width and height

### ISSUE THREAD

**Issue by jayarmstrong** [qewer33/Exquisite#18]
It took me a while to bend my head around the default naming and took a lot more time guessing and what I needed to do, until I read the note about these referring to width and height.

Linguistically, when I read "rowSpan" I think of the number of _rows_ it will span, in other words, _height_. Similarly, "columnSpan" suggests width to me.

"Width" and "height" are very clear, and translate across languages much better too.

**Comment by qewer33** [comment]
Yeah I agree and will change, the current naming is kinda dumb on my part and requires a lengthy explanation (at the end of the readme).

One thing I'm kind of worried about is, renaming will probably break older written layouts unless I make the layout loading code check for two variable names but that doesn't sound like a very good idea. I'll see what I can do.

**Comment by qewer33** [comment]
This shouldn't matter now since a GUI layout editor implementation is underway.
