### ISSUE TITLE
weird behavior on 2+ monitors

### ISSUE THREAD

**Issue by kupiqu** [qewer33/Exquisite#20]
Exquisite works great on a single monitorr but when I tried on 2 monitors it didn't work as expected (windows moved to the other monitor, also size and location were not reliable). Could you please check?

**Comment by qewer33** [comment]
Interesting, that shouldn't happen but I'll need to check for myself. Are you on Wayland or X11?

**Comment by kupiqu** [comment]
X11. Thanks for checking it out

**Comment by matiux** [comment]
Same issue on X11. I have two monitors and when I try to arrange windows on monitor A, all windows on monitor B move on monitor A ~~adapting to chosen layout~~. For example, I have 2 windows on monitor A and 1 windows on monitor B. On monitor A I chose a layout with two rows arranged vertically. The window of monitor B move on monitor A, so I have three windows on monitor A and only two arranged.

**Comment by Masiosare** [comment]
Plus 1, can confirm. there might be an issue on window selection, not sure if it's checking for all windows or only the windows in the current desktop.

**Comment by Akselmo** [comment]
Same here: On Wayland, even on separate screen focus toggled on in settings, Exquisite picks windows from the second monitor. I'd like the application tile windows only in the screen which Exquisite was activated on.

**Comment by qewer33** [comment]
This issue *should* be fixed now hopefully. If there is anyone available, I'd appreciate some testing. 

Not released yet so you will have to clone the repo, cd, run `./install.sh` and then run `kwin_x11 --replace` in a terminal or KRunner to restart KWin.

**Comment by jimt** [comment]
I _think_ [ee65da6](https://github.com/qewer33/Exquisite/commit/ee65da6586af6c0d4184a967eb5393c2ae3987b8) is working correctly on my two monitor X11 machine. Regardless of which monitor I am on when I launch Exquisite, the target window gets tiled within the monitor it was on.

**Comment by qewer33** [comment]
That should be the correct behavior, thanks for confirming!
