### ISSUE TITLE
[Feature Request] Option to hide titlebar when tiled

### ISSUE THREAD

**Issue by fenglengshun** [qewer33/Exquisite#21]
Hi, I've been using this on my devices for a while, and it's pretty cool. But on my older 768p laptop and secondary monitor, the titlebar takes so much space -- that's why I have [hide titles](https://github.com/bahamondev/hide-titles) kwin script installed and use global menu on top panel a la Unity.

It is possible to use Alt + F3 or a shortcut to manually enable the No Border option before using Exquisite to get the window to be tiled correctly without border, but it means that when you move it (say, with Meta + Left-Click shortcut) it will still have no border unlike hide titles which automatically restores the border when you exit maximized state or manually moved the window. And if you only enable No Border after tiling with Exquisite, the window get re-positioned incorrectly.

Is it possible to add a toggle that, when ticked, make sure that windows tiled with Exquisite will hide the window's titlebar? Maybe something based on the hide titles kwin script, since hide titles' behavior works very nice and seamlessly.

Thanks for your time regardless.

Edit: Something like:

![image](https://user-images.githubusercontent.com/26621899/199209570-bbc7558c-10a6-4c86-9e6d-49ceadac1d87.png)

**Comment by qewer33** [comment]
Nice idea and use case. Though I'll probably make it a checkbox that can be enabled in settings rather than a titlebar button. Tiled windows will re-gain their titlebars when untiled (if the "Remember window geometry" setting is on). I'm guessing that will satisfy your use case?

**Comment by fenglengshun** [comment]
It should. I just thought that a checkbox on the Exquisite window would make it more visible and easier to toggle on and off for others who want it on a case-by-case basis.

**Comment by qewer33** [comment]
Implemented now! Not released yet but you can try it out by following the manual install instructions on the README.
