### ISSUE TITLE
Unable to install on Debian 12 RC2 with KDE Plasma - file not found

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#23]
I am getting this error.

![image](https://github.com/qewer33/Exquisite/assets/83817/529c37ee-b905-477b-8770-a8f351010783)

**Comment by imthenachoman** [comment]
I was able to install using the file in the releases. But the store listing does not work.

**Comment by qewer33** [comment]
This is either an issue with your network or pling, are you able to install other KWin scripts or do you get the same error?
