### ISSUE TITLE
A few feature requests/ideas: show pop up under mouse.

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#24]
I just moved to Debian + KDE Plasma as my daily driver -- from Windows 10. 

I came across Exquisite and I love it. It is exquisite.

I had a feature idea I wanted to share.

I think it would be swell if pop up window show under/near the mouse. This would help with super ultrawide monitors.

**Comment by qewer33** [comment]
I wanted to add this before but the KWin API didn't provide any way to get the cursor. This has changed in 5.27. Added this feature (and made it default because it feels much more intuitive), will be in the next release!

**Comment by imthenachoman** [comment]
Ah. Nice. Thanks!
