### ISSUE TITLE
Bug: Some layout boxes are duplicated and some are missing. Also, how can we change the order of the layout boxes?

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#25]
I'm attaching my `qml` files here. As you can see from this screenshot, the 1st and 2nd layout are the same and they both link to `00.qml`. And `01.qml` is completely missing. 

![image](https://github.com/qewer33/Exquisite/assets/83817/d8df4529-ae65-491a-ae87-b70eddd49087)

Also, how can we change the order of the layout boxes? I tried naming them `00.qml`, `01.qml` but that isn't working as expected here.

[Archive.zip](https://github.com/qewer33/Exquisite/files/11499132/Archive.zip)

**Comment by qewer33** [comment]
I'm not sure how the duplication occurred but that naming style should work for ordering, have you restarted KWin after making the changes?

**Comment by imthenachoman** [comment]
Yes, I rebooted. But the issue persists. 

Is there anything I can do to help debug/test?

**Comment by qewer33** [comment]
Hmm this is very weird, I just tested with your archive and everything seems fine on me:

![image](https://github.com/qewer33/Exquisite/assets/69015181/97a174ea-0529-404c-8490-60e767f31707)
![image](https://github.com/qewer33/Exquisite/assets/69015181/2ffe34df-b503-400e-a636-71965189c78d)

**Comment by imthenachoman** [comment]
Try setting # of columns to 4? These are my settings:

![image](https://github.com/qewer33/Exquisite/assets/83817/2f085c5d-c10d-4fbf-9a71-b71d32fc520f)

**Comment by qewer33** [comment]
Hmm with 4 columns and the same settings, I'm still getting the correct result:

![image](https://github.com/qewer33/Exquisite/assets/69015181/9693119d-5c40-456c-98e2-d158d73c77e1)

**Comment by imthenachoman** [comment]
I just did a fresh install of Linux and was able to install this extension from the `Get New Scripts` button in system settings. Now it seems to show the layout. Previously I had installed from the file in the releases section of your repo.

**Comment by qewer33** [comment]
I also tried with the file in the releases (they should be the same with the one on the store either way) and had the correct result. The issue might have been something to do with your Plasma version. Glad it's resolved in a new install though! Closing the issue for now.
