### ISSUE TITLE
bug: enabling the Exquisite plugin makes the system "hang" for 30+ seconds during shutdown

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#26]
I was noticing my system would take 30+ seconds to reboot. It would get stuck on one part but I couldn't figure out where.

So I did a fresh/clean new install of Debian Bookworm testing (RC3) with KDE Plasma. The reboots were fast/normal, as expected.

The first and only thing I did was install Exquisite from system settings `Get New Scripts`.

If the script is enabled, the system gets "hung" for 30+ seconds during reboot before it finally reboots. I can't tell what it is hung/stuck on.

If I disable Exquisite, then the reboot time is normal/fast. 

I tested other KWin scripts, and none of them have an issue. So it must be something to do with Exquisite but I can't figure out what.

I'm happy to help debug if it'll help.

**Comment by qewer33** [comment]
Interesting issue. KWin manages Exquisite (Exquisite itself isn't a standalone program so KWin is probably what's hanging the system), can you run `kwin_x11 --replace` (on an X session, not Wayland) and then Ctrl+C to terminate it and see if it hangs, also would be great if you could send the final output (you can restart KWin again with the same command after killing it).

Also are you using X11 or Wayland?

**Comment by imthenachoman** [comment]
I am on Wayland. I am running Debian Bookworm/12 RC3.

I don't want to muck with my main system so I am going to create a VM and see if I can recreate the issue.

**Comment by imthenachoman** [comment]
Something else is at play but I can't figure it out. Sometimes the VM reboots quickly, sometimes it doesn't. I need to dig some more.

**Comment by imthenachoman** [comment]
It must have been a Debian thing. I am on openSUSE Tumbleweed now and it does not seem to be having issues.
