### ISSUE TITLE
Feature Request: Configurable padding/gaps with the layouts.

### ISSUE THREAD

**Issue by Kostrol** [qewer33/Exquisite#29]
Fantastic layout options, but I'm really missing an option to add padding to the tiled windows. Would love if this could be added at some point if there's not already an easy way to do it that I overlooked.

**Comment by ehanahamed** [comment]
@Kostrol I don't think adding padding/gaps to exquisite is needed, because exquisite is just a kwin addon, so other kwin addons work perfectly with exquisite, and therefore you can just use a seperate kwin script for gaps.

I use exquisite with another kwin script (https://github.com/nclarius/tile-gaps) for gaps between windows and gaps on the screen edges, and it works perfectly with exquisite.

**Comment by imthenachoman** [comment]
@ehanahamed That does not work on wayland. Also, not as efficient to have a 2nd script just for padding/gaps. I'd love to see padding/gaps in exquisite.

**Comment by ehanahamed** [comment]
@imthenachoman That's a valid opinion. I personally don't like wayland cause kde's implementation breaks some stuff (wayland itself is epic, its just kde on wayland thats kinda problematic). I'm just saying that while waiting for gaps to (hopefully) be added to Exquisite, if your using X11 and cannot live without padding/gaps, then other kwin scripts work (mostly) fine in combination with exquisite! I just don't think its a really important feature, but I'm not Qewer so my opinion shouldn't matter very much. ¯\\\_(シ)\_/¯

**Comment by imthenachoman** [comment]
@ehanahamed I too am starting to wonder if I should switch to X11 over Wayland.

**Comment by Kostrol** [comment]
> I use exquisite with another kwin script (https://github.com/nclarius/tile-gaps) for gaps between windows and gaps on the screen edges, and it works perfectly with exquisite.

I would if this worked without issues, I have tried a few and unfortunately this one causes windows to pin and stretch when moved around tiled windows. I think a native solution would work great with Exquisite. I am an nvidia and x11 user..

**Comment by qewer33** [comment]
This has now been implemented and will be on the next release.
