### ISSUE TITLE
[Suggestion] Add 1:2:1 layout for Ultrawide monitors

### ISSUE THREAD

**Issue by TacoCake** [qewer33/Exquisite#3]
I use a super-ultrawide monitor and I have a 3 column layout that I use daily, which looks like:

 > 25% of screen width |   50% of screen width  | 25% of screen width 

On a super ultrawide (5120x1440), the aspect ratio for each window looks like this:

 >  8:9 |   16:9   | 8:9 

I would love for this layout to be added, since it's the one I use the most, I'm fine with it being an optional toggle in the settings. 
I'm willing to do some testing if necessary.

Thanks in advance!

EDIT: I am aware you can create custom layouts, but I feel that this one would be important enough to warrant being included by default.

**Comment by qewer33** [comment]
I actually added that layout before release, but then decided it was useless (I really did forget there were bigger monitors than my laptop screen lol) and scrapped it. Re added it now along with another new layout ([2ebdda2](https://github.com/qewer33/Exquisite/commit/2ebdda290f72c69f264a0a0cf30dde22543daa45)).
