### ISSUE TITLE
I'm working on a Windows 10 clone written in AutoHotKey. Are you okay with me releasing it and linking to yours?

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#30]
I use Linux as my daily driver but I have to use Windows on some machines.

I love Exquisite so much that I wanted a clone of it for Windows 11. 

I don't know AHK that much but I got some help from someone to write a clone for me.

I'm thinking to put it on GitHub so others can use if they like.

My plan is to call it `ExquisiteW` for windows. Thoughts?

**Comment by imthenachoman** [comment]
![image](https://github.com/qewer33/Exquisite/assets/83817/12debbdd-e456-4508-aaef-10684babfb71)

**Comment by qewer33** [comment]
Really cool and looks great so far! You can use the name, it's fine by me.

Just wanted to ask, Exquisite was actually initially inspired by the built-in Windows 11 tiling, is there a reason why that doesn't satisfy your need?

Also the send to monitor option seems like a nice feature. I'm currently busy with other projects but I'll add it to my list of stuff to add when I resume working on Exquisite.

**Comment by imthenachoman** [comment]
> Really cool and looks great so far! You can use the name, it's fine by me.

Thanks!

> Just wanted to ask, Exquisite was actually initially inspired by the built-in Windows 11 tiling, is there a reason why that doesn't satisfy your need?

I am on Windows 10 and am going to try to avoid going to 11 for as long as I can. Even the one on Windows 11 does not have enough features. The one I am working on for Windows, the pop up shows right under your mouse. So it's a lot faster to move a window. Even with PowerToys, you have to drag the window all the way to the other side of the screen.

> Also the send to monitor option seems like a nice feature. I'm currently busy with other projects but I'll add it to my list of stuff to add when I resume working on Exquisite.

Thanks. I was going to suggest that to you for Exquisite. The other one is above the zone selector it shows the name of the active application that will be moved. This way you don't accidentally move the wrong thing.

I'll share link once I have it done.

**Comment by qewer33** [comment]
> I am on Windows 10 and am going to try to avoid going to 11 for as long as I can. Even the one on Windows 11 does not have enough features. The one I am working on for Windows, the pop up shows right under your mouse. So it's a lot faster to move a window. Even with PowerToys, you have to drag the window all the way to the other side of the screen.

Ah alright. Makes sense.

> The other one is above the zone selector it shows the name of the active application that will be moved. This way you don't accidentally move the wrong thing.

Ooo that also sounds like a good feature.

> I'll share link once I have it done.

Looking forward to it!

**Comment by imthenachoman** [comment]
Launched. Tell me what you think.

https://github.com/imthenachoman/ExquisiteW

![GUI with multiple monitors](https://github.com/qewer33/Exquisite/assets/83817/4974eb57-173a-4feb-a376-e78812d0c470)
