### ISSUE TITLE
Integration of built-in tiling in plasma 5.27

### ISSUE THREAD

**Issue by CavaleriOmar** [qewer33/Exquisite#32]
I love the handling of tiling so "manual" compared to many of the scripts available for kWin (to me Polonium for example often goes awry using a 16:10 notebook with a 21:9 external screen), and the tiling functionality present since the 5.27 release of plasma is fantastic... and Exquisite seems born to integrate with it: one could keep a basic layout and then modify it on the fly with the tiling of plasma 5.27, perhaps saving with Exquisite a layout obtained

**Comment by qewer33** [comment]
I am personally dissatisfied with the default KWin tiling introduced in 5.27 and find it quite buggy. Exquisite uses it's own tiling system and this will probably not change in the near future.

Maybe after Plasma 6 releases, I will reconsider this but for now it's not planned.
