### ISSUE TITLE
keyboard activator for zone when Exquisite is active

### ISSUE THREAD

**Issue by imthenachoman** [qewer33/Exquisite#33]
As mentioned in https://github.com/qewer33/Exquisite/issues/30, I created a Windows clone of Exquisite.

One feature I added in the Windows version is that when the GUI is active, you can quickly select a zone with a keyboard key press.

I think it would be wicked to add this to Exquisite.

**Comment by qewer33** [comment]
Closing this in favor of https://github.com/qewer33/Exquisite/issues/34
