### ISSUE TITLE
[0.5 Release] Requested and Indev Features

### ISSUE THREAD

**Issue by qewer33** [qewer33/Exquisite#34]
- [x] Wayland compatibility for all features
- [x] Open Exquisite under mouse cursor
   - Only works with Plasma version above 5.27.5 since the necessary API didn't exist in older versions
- [x] Show active window icon and title in Exquisite header
- [x] Close Exquisite with ESC
- [x] Assign keys to layout windows
- [x] Built-in window padding/gaps preference
- [x] Multi Monitor support
   - I can implement this but I don't have multiple monitors so it'll be difficult to test

Related issues:
https://github.com/qewer33/Exquisite/issues/11
https://github.com/qewer33/Exquisite/issues/17
https://github.com/qewer33/Exquisite/issues/29
https://github.com/qewer33/Exquisite/issues/33

**Comment by qewer33** [comment]
@imthenachoman feel free to comment here!

**Comment by qewer33** [comment]
Preview of entries 2 and 3:

[vokoscreenNG-2024-01-23_17-48-46.webm](https://github.com/qewer33/Exquisite/assets/69015181/832e9c5e-a5ef-48c4-b402-c9590463dc15)

**Comment by imthenachoman** [comment]
I freaking love this. Thank you!

**Comment by qewer33** [comment]
Window tile shortcuts preview

[vokoscreenNG-2024-01-25_16-22-42.webm](https://github.com/qewer33/Exquisite/assets/69015181/7315b9d7-6e74-4da1-8a96-9929565c47d5)

**Comment by imthenachoman** [comment]
This looks great!

Do the shortcuts only work when Exquisite is active? Meaning if the shortcuts are also used in other apps, it won't be an issue, right? 

And can the shortcuts be anything like a letter, number, a combination?

**Comment by qewer33** [comment]
The shortcuts only work when Exquisite is active, so you have to activate Exquisite first and then use the shortcuts. This is a limitation of KWin, the API doesn't allow for custom global shortcuts sadly. But it shouldn't be too big of an issue if you bind Exquisite to something easy to reach (say Shift+A), that way you can quickly toggle Exquisite, select windows, press a few tile shortcuts and ESC out. Certainly a bit more cumbersome than just pressing the shortcuts directly though, yeah. 

Shortcuts (for now) can have one modifier (Ctrl, Shift, Alt, Meta) or none and can have one key (any keyboard key defined by Qt). I can implement modifier and key combinations if you want.

**Comment by imthenachoman** [comment]
> The shortcuts only work when Exquisite is active

Awesome!

> Shortcuts (for now) can have one modifier (Ctrl, Shift, Alt, Meta) or none and can have one key (any keyboard key defined by Qt). I can implement modifier and key combinations if you want.

Awesome. That works. I like the idea of a single letter so it's easy and fast. Open Exquisite, press a keyboard letter, and done.

**Comment by qewer33** [comment]
@imthenachoman I will do a final release next week but if you want to test the requested features early you can install https://github.com/qewer33/Exquisite/raw/main/exquisite.kwinscript and run `kpackagetool5 -u exquisite.kwinscript`.

**Comment by zelch** [comment]
@qewer33 I would be happy to do any testing you wanted on multi-monitor support.

Though, I do have to say, working on kwin scripts is rapidly convincing me to spin up a VM.

**Comment by Tellinq** [comment]
I'm also willing to help test out multi monitor support if you ever need it!

**Comment by zelch** [comment]
I may have a PR that addresses this in a few days.

It's mostly written, and it has been tested a bit, but it needs more testing and another look through while I commit the pieces, and I have a few distractions at the moment.

(It's actually about an entirely unrelated feature, but one that really breaks with multiple monitors.  I think I ended up fixing a few different things once I got a VM setup for at least the single monitor use cases.)

**Comment by zelch** [comment]
#35 addresses the multiple monitors case, along with several other items which I needed to make my setup more 'me' friendly.

Right now, my biggest remaining gripe is that under Wayland, we are spamming the logs quite badly with 'This plugin does not support raise()', because that gets printed every single time we call raise.

I would happily make a wrapper function that only called raise if we were in a X11 session...  Except I can't find a way to detect Wayland vs X11 in a kwin script.

**Comment by qewer33** [comment]
Woah, @zelch thanks a lot for the PR! I'll try to review it in my spare time

**Comment by qewer33** [comment]
> I would happily make a wrapper function that only called raise if we were in a X11 session... Except I can't find a way to detect Wayland vs X11 in a kwin script.

This can probably be implemented with a data source and a shell script. Take a look how the "Restart KWin" button is implemented.

**Comment by imthenachoman** [comment]
@qewer33 Curious when you plan on doing final release for this to prod?

**Comment by qewer33** [comment]
@imthenachoman currently trying to port Exquisite to Plasma 6, it's proving to be somewhat difficult. But thank you for the reminder I'll update the Plasma 5 package in the store

**Comment by imthenachoman** [comment]
Any luck on pushing the new version to the store?

**Comment by qewer33** [comment]
> Any luck on pushing the new version to the store?

Pushed!

**Comment by imthenachoman** [comment]
I am getting flickering when I activate it. Any idea what might be causing it?

**Comment by qewer33** [comment]
> I am getting flickering when I activate it. Any idea what might be causing it? 

Flickering? Does it not open? Or is it a visual glitch? A video and/or kwin log (when run via terminal with kwin_x11 --replace) would be very helpful.

**Comment by zelch** [comment]
And is the flickering on Wayland or X11?

**Comment by imthenachoman** [comment]
I'm on Wayland. When I open Exquisite, the entire screen flickers. Let me see if I can get a video.

**Comment by imthenachoman** [comment]
Couldn't get screen recorder working. Took a video from phone. 

https://drive.google.com/file/d/1p-HryWsZHshvPJzu9TQ40iQ3NFC7en1b/view?usp=sharing

**Comment by qewer33** [comment]
Super weird. I can't seem to reproduce it on Fedora 38 Wayland. @zelch can you also try?

**Comment by imthenachoman** [comment]
It could be something up with my computer. I will do some more research/debugging.

**Comment by zelch** [comment]
Alright...

What video card are you using, and what driver version?

I'm going to take a wild guess that you're on an nVidia card, and that the driver version is going to be significant.

**Comment by imthenachoman** [comment]
I am running an Intel Core i5-8500 with an integrated Intel UHD Graphics 630.

Don't spend too much time on debugging this. I bet it's something specific to my computer .I've been looking for an excuse to upgrade my PC. I want a new gaming PC. :)

![image](https://github.com/qewer33/Exquisite/assets/83817/489af91b-3efa-425b-acc1-27d298387dee)

**Comment by imthenachoman** [comment]
So the flickering doesn't happen in X11 and all the Debian experts are telling me I should stick with X11 for Debian stable with KDE. So I suppose I will do that.

**Comment by imthenachoman** [comment]
@qewer33 Love the changes. I think I see two bugs:

- Unchecking `Show layout names in layout grid` just moves the layout names to the bottom
- Tiling a window using the keyboard shortcut (e.g. `A`) does not hide Exquisite even if `Hide after tiling a window` is checked.

Minor issue but wanted to report.

Great work with this. Very happy!

**Comment by zelch** [comment]
@qewer33 The change to the text of kcfg_nameAbove in 645af73d66b5f640340da57eff0a501b5b8a9d5c needs to be reverted.

**Comment by zelch** [comment]
I see the bug related to tiling using the keyboard shortcut, working on that now.

There is an almost identical bug for 'Hide after tiling a layout', but that one looks a lot harder to get right for the keyboard shortcut case.

I'll test the fix for the 'Hide after tiling a window', throw in the fix for kcfg_nameAbove, and try and get a PR out sometime today.

**Comment by qewer33** [comment]
> @qewer33 The change to the text of kcfg_nameAbove in 645af73d66b5f640340da57eff0a501b5b8a9d5c needs to be reverted.

Yeah I noticed that after pushing the release. I'll look at your PR tomorrow but do we really need a configuration option for showing the labels in the top/bottom? IMHO just having them be on the bottom (or top, doesn't really matter but bottom looks cleaner imo) and having an option for hiding them makes way more sense.

**Comment by qewer33** [comment]
Also @zelch have you tried anything or had any luck regarding a Plasma 6 port? I was getting really weird and nonsensical errors the last time I tried. Kinda busy rn so I'll probably take a detailed next month but in the meantime if you want, you can do some tinkering!

**Comment by qewer33** [comment]
> Great work with this. Very happy!

Thanks and I'm really glad you're enjoying it @imthenachoman ! And sorry for the late release. I thought you were already using the unreleased package and my intention was to release the Plasma 5 version together with a Plasma 6 port but that's going to take a bit longer anyway 😅

**Comment by imthenachoman** [comment]
@qewer33 No issues at all. This is my main production daily driver so I try to only run things the official/right way. I don't have time to muck with things breaking.

**Comment by zelch** [comment]
> > @qewer33 The change to the text of kcfg_nameAbove in [645af73](https://github.com/qewer33/Exquisite/commit/645af73d66b5f640340da57eff0a501b5b8a9d5c) needs to be reverted.
> 
> Yeah I noticed that after pushing the release. I'll look at your PR tomorrow but do we really need a configuration option for showing the labels in the top/bottom? IMHO just having them be on the bottom (or top, doesn't really matter but bottom looks cleaner imo) and having an option for hiding them makes way more sense.

I prefer names on top, you prefer names on bottom, and the code for the configuration option already exists. :)

That said, I do think that an option to hide them entirely would make sense, and in that case, what we want is an option to select top/bottom/none, I can take a look at implementing that sometime here if you're interested.

> Also @zelch have you tried anything or had any luck regarding a Plasma 6 port? I was getting really weird and nonsensical errors the last time I tried. Kinda busy rn so I'll probably take a detailed next month but in the meantime if you want, you can do some tinkering!

I have not, I'm on Debian unstable, and Plasma 6 likely won't get packaged until the 6.1 release, or at least the beta for it.

The beta release is scheduled for the 23rd of this month, and the 6.1.0 release is scheduled for 2024-06-18, so exactly a month from now.

I expect that I'll be porting everything that I'm currently using over as soon as that happens. :)

**Comment by zelch** [comment]
@qewer33 Alright, I've done a quick implementation of making it a drop down, but I wonder if you have any preferences on the appearance in the configuration menu.

![image](https://github.com/qewer33/Exquisite/assets/1652987/262425cc-ce0e-465f-9a9d-c5d38016d690)

**Comment by qewer33** [comment]
> @qewer33 Alright, I've done a quick implementation of making it a drop down, but I wonder if you have any preferences on the appearance in the configuration menu.
> 

I have a better idea, I'll implement it.

Edit: Implemented

![image](https://github.com/qewer33/Exquisite/assets/69015181/b67741e8-a4e4-4a7d-b8d3-efaa6c3af5d1)

**Comment by zelch** [comment]
As an aside, I think we can now check off multi-monitor support, as the `screen` property of a layout now specifies which display to use. :)

**Comment by imthenachoman** [comment]
I have a second Debian box now. I use it for testing stuff. I'm happy to user/pressure test your commits if you can tell me how to install them.

**Comment by imthenachoman** [comment]
I know y'all are working on bug fixes but anyway you could tell me what lines to fix to make it auto hide after using a keyboard shortcut?

**Comment by zelch** [comment]
@imthenachoman In the settings screen, select the Behavior tab, and check 'Hide after tiling a window'.

**Comment by imthenachoman** [comment]
@zelch I have that enabled. The bug is that when you tile a window using the keyboard shortcut, it does not hide. It only hides when you click. I was hoping for a quick fix for that? Something I could just update in the code in my installation?

**Comment by zelch** [comment]
@imthenachoman ... I already fixed that bug, and the fix is in the most recent release.

Can you test again with the current version and confirm that it's still not working?  

If so, please enable the debug logging option under behavior, apply, then bring up the tile dialog, tile a window with the shortcut, manually close said dialog, and attach the resulting kwin logs.

**Comment by imthenachoman** [comment]
In release 0.5? Where? How do I update or get it?

And I don't see debug logging option anywhere. 

![image](https://github.com/qewer33/Exquisite/assets/83817/0d52be9d-3bc0-4c5c-85da-436d44119677)

**Comment by zelch** [comment]
Alright, you're definitely not running the current version.

If you start up Discover, then under Update (bottom left of the window) you should have the option to update kwin extensions, including Exquisite.

**Comment by imthenachoman** [comment]
Nope. Nothing for Exquisite. When did you update it?

I updated to 0.5 on May 17. Then I saw your comments about fixing that bug. But I didn't see anything about an update? The store still has 0.5.

![image](https://github.com/qewer33/Exquisite/assets/83817/3c7195ba-802e-4b25-9b1f-e92f76f0729f)

**Comment by zelch** [comment]
Ah, hrm.

@qewer33 Could we get a 0.6 release with the current git head? :)

I've got some minor changes I still need to write commit messages for, but nothing even remotely critical.

(It's a matter of documentation, and of attempting (and largely failing for Reasons™) to format the case where multiple modifiers are used for a tile shortcut.)

**Comment by imthenachoman** [comment]
No need to push a new release on my account. I was just hoping to see the lines changed to fix that bug so I could make them on my end.

**Comment by qewer33** [comment]
Sorry for the inactivity, finally free from my university exam and got time to work on Exquisite again :sweat_smile:

@zelch do you have anything commit/PR? If not I'll upload a new release

**Comment by imthenachoman** [comment]
Is there anything I can do to get the auto close after keyboard shortcut tiling to work? Right now it will tile when I select the keyboard shortcut, but the Exquisite window stays open.

**Comment by zelch** [comment]
@qewer33 I do, but I'm still trying to figure out a UI problem.

The easy part is the documentation:
Just replacing:
> - `shortcutModifier`: Optional parameter that defines the modifier that needs to be pressed in order for `shortcutKey` to work. Can be one of the following: `Qt.ControlModifier`, `Qt.ShiftModifier`, `Qt.AltModifier`, `Qt.MetaModifier`. If you want to assign a single key without a modifier as a shortcut to a window, leave this parameter empty.

With:
>- `shortcutModifier`: Optional parameter that defines the modifier or modifiers that needs to be pressed in order for `shortcutKey` to work. Can be one or more of the following: `Qt.ControlModifier`, `Qt.ShiftModifier`, `Qt.AltModifier`, `Qt.MetaModifier`. If you want to require multiple modifiers, separate them with `|`, like: `qt.ControlModifier | Qt.ShiftModifier`. If you want to assign a single key with
out a modifier as a shortcut to a window, leave this parameter empty.

And that actually works today.

But what doesn't work is the rendering of the shortcut in the window layout.

My first try at fixing that works fine...  Except that printing Ctrl+Alt+F1 really doesn't fit in the available space.

Rendering that as C+A+F1 would fit better, but would be more ambiguous, and would change the simpler case of things like Alt+F1.

Any thoughts?

**Comment by qewer33** [comment]
@zelch does breaking the text into multiple lines not work? Or maybe we can make it trancunate with ellipsis and show full shortcut text in a tooltip when it's hovered

I've picked up trying to port Exquisite to Plasma 6 again but it's proving to be really difficult with the almost non-existent KWin API documentation changelog...

**Comment by zelch** [comment]
@qewer33 There's no good way that I can find to break it into multiple lines.

The tooltip on hovered sounds like a good plan though.

Where are you on the port to Plasma 6?  Debian Experimental finally got Plasma 6, so I'm working my way through the widgets and extensions that I'm used to, and Exquisite is next on my list. :)

**Comment by A-Byte-Sized** [comment]
It's been a bit since the last update here; how is the Plasma 6 port going? I might take a look into it as I miss Exquisite.

**Comment by qewer33** [comment]
> It's been a bit since the last update here; how is the Plasma 6 port going? I might take a look into it as I miss Exquisite.

Yeah uhh I have kinda been stuck... I got it to run without any errors on Plasma 6 but I couldn't get the Exquisite dialog to show no matter what I tried. I will push my changes to a new branch soon. Would appreciate any help!

**Comment by A-Byte-Sized** [comment]
Sounds good, let me know whenever you've pushed a branch and I'll take a whack at it!

**Comment by zelch** [comment]
I would also love to take a crack at the problem, since it sounds like you're in a decent place progress wise! :)

**Comment by qewer33** [comment]
@A-Byte-Sized and @zelch I have pushed my changes to the `plasma6` branch. We can use the [Plasma 6 issue](https://github.com/qewer33/Exquisite/issues/36) as a tracker, you can comment about your findings there (also please comment if you get any unexpected errors on the current commit). Thank you guys for your interest! 

https://github.com/qewer33/Exquisite/tree/plasma6

**Comment by qewer33** [comment]
Also seems like this issue can be closed.

**Comment by imthenachoman** [comment]
I was wondering if there was an update pushed? I'm still having that issue where it does not auto close when using keyboard shortcut.

**Comment by imthenachoman** [comment]
Just checking? And does this work on KDE 6 yet?
