### ISSUE TITLE
help creating a custom grid

### ISSUE THREAD

**Issue by jayarmstrong** [qewer33/Exquisite#6]
Hi,
It's working great with defaults but I can't seem to create a 2x3 grid layout. It renders it with gaps between windows and runs off screen (the preview accurately shows the result). Also, after editing my custom layout file, the Exquisite preview doesn't update to reflect the changes... that might be a separate issue.

Here's my attempted layout:
```
import QtQuick 2.6

Item {
    property string name: "2 x 3"
    property var windows: [
        {
            row: 0,
            rowSpan: 4,
            column: 0,
            columnSpan: 6
        },
        {
            row: 0,
            rowSpan: 4,
            column: 4,
            columnSpan: 6
        },
        {
            row: 0,
            rowSpan: 4,
            column: 8,
            columnSpan: 6
        },
        {
            row: 6,
            rowSpan: 4,
            column: 0,
            columnSpan: 6
        },
        {
            row: 6,
            rowSpan: 4,
            column: 4,
            columnSpan: 6
        },
        {
            row: 6,
            rowSpan: 4,
            column: 8,
            columnSpan: 6
        }
    ]
}
![strange](https://user-images.githubusercontent.com/2851379/179167173-1e42e772-dfe4-4707-8fb4-e1af21108991.png)

```
Here's what that creates:
![strange](https://user-images.githubusercontent.com/2851379/179167173-1e42e772-dfe4-4707-8fb4-e1af21108991.png)

**Comment by qewer33** [comment]
Hmm, that is indeed weird. I'm not on my main setup rn but I will take a look once I can
> Also, after editing my custom layout file, the Exquisite preview doesn't update to reflect the changes... that might be a separate issue

Yeah KWin needs to be restarted to see the changes. I will add a refresh button on the header bar to make that a bit easier

> (the preview accurately shows the result)

Also about this, did you use `qmlscene` for the preview?

**Comment by qewer33** [comment]
Just tried and it seems to work fine for me:
![image](https://user-images.githubusercontent.com/69015181/179350240-e7eabb64-a556-4aee-8ff3-6c65a2d9ae44.png)
Did you restart KWin after you made changes? It might still be rendering one of your older attempts

**Comment by jayarmstrong** [comment]
I didn't restart Kwin, just disabled and re-enabled Exquisite. I'll see if that works.

Not sure where qmlscene fits in. This is on a fresh openSUSE / Plasma 5.24 install.

**Comment by Zetaphor** [comment]
Can also verify this works for me after restarting KWin. @jayarmstrong maybe you were looking at a previous revision and didn't restart KWin to see your latest changes? I don't think disabling/enabling KWin in system settings is enough.

See this section of the README:
https://github.com/qewer33/Exquisite#installation

**Comment by qewer33** [comment]
Closing this issue

**Comment by jayarmstrong** [comment]
Got it working. Thanks! Just got back to testing it and found that Exquisite will only parse the QML layout files (at least for creating the layout thumbnails) when they are first created. I simply saved all changes to new files and it parsed them (and any deletions of other QML files) immediately. That's convenient for experimenting and doesn't require restarting Kwin.
